function [TimeDEVICE_1Samplerate1CH1,F8612CH2,F8145CH3,F8146CH4,PosXCH5,SpeedXCH6] = importfile2(filename, startRow, endRow)
%IMPORTFILE2 Import numeric data from a text file as column vectors.
%   [TIMEDEVICE_1SAMPLERATE1CH1,F8612CH2,F8145CH3,F8146CH4,POSXCH5,SPEEDXCH6]
%   = IMPORTFILE2(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMEDEVICE_1SAMPLERATE1CH1,F8612CH2,F8145CH3,F8146CH4,POSXCH5,SPEEDXCH6]
%   = IMPORTFILE2(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [TimeDEVICE_1Samplerate1CH1,F8612CH2,F8145CH3,F8146CH4,PosXCH5,SpeedXCH6]
%   = importfile2('hopp.asc',7, 35);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/01/13 20:07:34

%% Initialize variables.
delimiter = '\t';
if nargin<=2
	startRow = 7;
	endRow = 35;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
for block=2:length(startRow)
	frewind(fileID);
	textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
	dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'ReturnOnError', false);
	for col=1:length(dataArray)
		dataArray{col} = [dataArray{col};dataArrayBlock{col}];
	end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
	raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));


%% Split data into numeric and cell columns.
rawNumericColumns = {};
rawCellColumns = raw(:, [1,2,3,4,5,6]);


%% Allocate imported array to column variable names
TimeDEVICE_1Samplerate1CH1 = rawCellColumns(:, 1);
F8612CH2 = rawCellColumns(:, 2);
F8145CH3 = rawCellColumns(:, 3);
F8146CH4 = rawCellColumns(:, 4);
PosXCH5 = rawCellColumns(:, 5);
SpeedXCH6 = rawCellColumns(:, 6);


