
%CREATEFITS(VAR,SURGE,SWAY,FORCE)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : var
%      Y Output: surge
%  Data for 'untitled fit 2' fit:
%      X Input : var
%      Y Output: sway
%  Data for 'untitled fit 3' fit:
%      X Input : var
%      Y Output: force
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Jan-2015 14:44:49

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 3, 1 );
gof = struct( 'sse', cell( 3, 1 ), ...
	'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( var, surge );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [1.0972118883943 1 1.56446002444225];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{1}, xData, yData, 'predobs' );
legend( h, 'surge vs. var', 'untitled fit 1', 'Lower bounds (untitled fit 1)', 'Upper bounds (untitled fit 1)', 'Location', 'NorthEast' );
% Label axes
xlabel var
ylabel surge
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{1}, xData, yData, 'residuals' );
legend( h, 'untitled fit 1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel var
ylabel surge
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( var, sway );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf];
opts.StartPoint = [0.793906099243828 1 0.0226588139228348];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 2' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{2}, xData, yData, 'predobs' );
legend( h, 'sway vs. var', 'untitled fit 2', 'Lower bounds (untitled fit 2)', 'Upper bounds (untitled fit 2)', 'Location', 'NorthEast' );
% Label axes
xlabel var
ylabel sway
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{2}, xData, yData, 'residuals' );
legend( h, 'untitled fit 2 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel var
ylabel sway
grid on

%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( var, force );

% Set up fittype and options.
ft = fittype( 'sin3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [1.58173219738403 0.5 1.57839846818374 0.742045666669895 1 -1.60252134914397 0.206543390715681 2 1.52513349969915];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, xData, yData, 'predobs' );
legend( h, 'force vs. var', 'untitled fit 3', 'Lower bounds (untitled fit 3)', 'Upper bounds (untitled fit 3)', 'Location', 'NorthEast' );
% Label axes
xlabel var
ylabel force
grid on


