function [fitresult, gof] = createFitPoly5(x, y)
%CREATEFIT(SPEED,RESISTANCE)
%  Create a fit.
%
%  Data for 'Resistance fitting' fit:
%      X Input : speed
%      Y Output: resistance
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Jan-2015 16:27:02


%% Fit: 'Resistance fitting'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly5' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Lower = [-Inf -Inf -Inf -Inf -Inf 0];
opts.Upper = [Inf Inf Inf Inf Inf 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Resistance fitting - 5rd degree polynomial' );

% Set default text interpreter
set(0,'defaulttextinterpreter','latex');

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData, 'predobs' );
handle = legend( h, 'resistance vs. speed', 'Resistance fitting', 'Location', 'NorthWest' );
set(handle,'Interpreter','latex')
% Label axes
xlabel speed
ylabel resistance
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
handle = legend( h, 'Resistance fitting - residuals', 'Zero Line', 'Location', 'SouthEast' );
set(handle,'Interpreter','latex')
% Label axes
xlabel speed
ylabel resistance
grid on


